import { createClient } from "@libsql/client";

const client = createClient({
  url: process.env.TURSO_DATABASE_URL,
  authToken: process.env.TURSO_AUTH_TOKEN,
});

const statements = [
  `CREATE TABLE IF NOT EXISTS "users" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT, "email" TEXT NOT NULL, "passwordHash" TEXT, "role" TEXT NOT NULL DEFAULT 'MEMBER', "avatar" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS "contacts" ("id" TEXT NOT NULL PRIMARY KEY, "firstName" TEXT NOT NULL, "lastName" TEXT NOT NULL, "email" TEXT NOT NULL, "phone" TEXT, "company" TEXT, "jobTitle" TEXT, "source" TEXT NOT NULL DEFAULT 'MANUAL', "sourceCampaign" TEXT, "sourceAd" TEXT, "sourceKeyword" TEXT, "utmSource" TEXT, "utmMedium" TEXT, "utmCampaign" TEXT, "utmContent" TEXT, "utmTerm" TEXT, "gclid" TEXT, "fbclid" TEXT, "tags" TEXT NOT NULL DEFAULT '[]', "customFields" TEXT NOT NULL DEFAULT '{}', "lifecycleStage" TEXT NOT NULL DEFAULT 'LEAD', "leadScore" INTEGER NOT NULL DEFAULT 0, "acquisitionCost" REAL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS "pipelines" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "stages" TEXT NOT NULL DEFAULT '[]', "isDefault" BOOLEAN NOT NULL DEFAULT false, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS "deals" ("id" TEXT NOT NULL PRIMARY KEY, "contactId" TEXT NOT NULL, "title" TEXT NOT NULL, "value" REAL NOT NULL, "currency" TEXT NOT NULL DEFAULT 'USD', "stage" TEXT NOT NULL DEFAULT 'LEAD', "pipelineId" TEXT NOT NULL, "probability" INTEGER NOT NULL DEFAULT 0, "expectedCloseDate" DATETIME, "actualCloseDate" DATETIME, "lostReason" TEXT, "sourcePlatform" TEXT, "sourceCampaign" TEXT, "assignedToId" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, FOREIGN KEY ("contactId") REFERENCES "contacts" ("id") ON DELETE CASCADE, FOREIGN KEY ("pipelineId") REFERENCES "pipelines" ("id"), FOREIGN KEY ("assignedToId") REFERENCES "users" ("id") ON DELETE SET NULL)`,
  `CREATE TABLE IF NOT EXISTS "activities" ("id" TEXT NOT NULL PRIMARY KEY, "contactId" TEXT NOT NULL, "dealId" TEXT, "type" TEXT NOT NULL, "subject" TEXT NOT NULL, "body" TEXT, "outcome" TEXT, "dueDate" DATETIME, "completedAt" DATETIME, "assignedToId" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("contactId") REFERENCES "contacts" ("id") ON DELETE CASCADE, FOREIGN KEY ("dealId") REFERENCES "deals" ("id") ON DELETE SET NULL, FOREIGN KEY ("assignedToId") REFERENCES "users" ("id") ON DELETE SET NULL)`,
  `CREATE TABLE IF NOT EXISTS "ad_accounts" ("id" TEXT NOT NULL PRIMARY KEY, "platform" TEXT NOT NULL, "accountId" TEXT NOT NULL, "accountName" TEXT NOT NULL, "accessToken" TEXT, "refreshToken" TEXT, "tokenExpiresAt" DATETIME, "currency" TEXT NOT NULL DEFAULT 'USD', "timezone" TEXT NOT NULL DEFAULT 'America/New_York', "isActive" BOOLEAN NOT NULL DEFAULT true, "lastSyncedAt" DATETIME, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS "campaigns" ("id" TEXT NOT NULL PRIMARY KEY, "adAccountId" TEXT NOT NULL, "platform" TEXT NOT NULL, "externalId" TEXT, "name" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'DRAFT', "objective" TEXT, "budgetDaily" REAL, "budgetTotal" REAL, "startDate" DATETIME, "endDate" DATETIME, "targeting" TEXT NOT NULL DEFAULT '{}', "metrics" TEXT NOT NULL DEFAULT '{}', "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, FOREIGN KEY ("adAccountId") REFERENCES "ad_accounts" ("id") ON DELETE CASCADE)`,
  `CREATE TABLE IF NOT EXISTS "ad_sets" ("id" TEXT NOT NULL PRIMARY KEY, "campaignId" TEXT NOT NULL, "name" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'ACTIVE', "targeting" TEXT NOT NULL DEFAULT '{}', "budgetDaily" REAL, "bidAmount" REAL, "bidStrategy" TEXT, "metrics" TEXT NOT NULL DEFAULT '{}', "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, FOREIGN KEY ("campaignId") REFERENCES "campaigns" ("id") ON DELETE CASCADE)`,
  `CREATE TABLE IF NOT EXISTS "ads" ("id" TEXT NOT NULL PRIMARY KEY, "adSetId" TEXT NOT NULL, "name" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'ACTIVE', "creative" TEXT NOT NULL DEFAULT '{}', "metrics" TEXT NOT NULL DEFAULT '{}', "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, FOREIGN KEY ("adSetId") REFERENCES "ad_sets" ("id") ON DELETE CASCADE)`,
  `CREATE TABLE IF NOT EXISTS "campaign_metrics" ("id" TEXT NOT NULL PRIMARY KEY, "campaignId" TEXT NOT NULL, "date" DATETIME NOT NULL, "impressions" INTEGER NOT NULL DEFAULT 0, "clicks" INTEGER NOT NULL DEFAULT 0, "ctr" REAL NOT NULL DEFAULT 0, "cpc" REAL NOT NULL DEFAULT 0, "cpm" REAL NOT NULL DEFAULT 0, "spend" REAL NOT NULL DEFAULT 0, "conversions" INTEGER NOT NULL DEFAULT 0, "conversionValue" REAL NOT NULL DEFAULT 0, "roas" REAL NOT NULL DEFAULT 0, "cpa" REAL NOT NULL DEFAULT 0, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("campaignId") REFERENCES "campaigns" ("id") ON DELETE CASCADE)`,
  `CREATE TABLE IF NOT EXISTS "optimization_logs" ("id" TEXT NOT NULL PRIMARY KEY, "campaignId" TEXT, "ruleName" TEXT NOT NULL, "actionType" TEXT NOT NULL, "description" TEXT NOT NULL, "oldValue" TEXT, "newValue" TEXT, "impact" TEXT, "canUndo" BOOLEAN NOT NULL DEFAULT true, "undone" BOOLEAN NOT NULL DEFAULT false, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("campaignId") REFERENCES "campaigns" ("id") ON DELETE SET NULL)`,
  `CREATE TABLE IF NOT EXISTS "optimization_rules" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "type" TEXT NOT NULL, "conditions" TEXT NOT NULL DEFAULT '[]', "actions" TEXT NOT NULL DEFAULT '[]', "isEnabled" BOOLEAN NOT NULL DEFAULT true, "lastTriggered" DATETIME, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS "social_accounts" ("id" TEXT NOT NULL PRIMARY KEY, "platform" TEXT NOT NULL, "accountId" TEXT NOT NULL, "accountName" TEXT NOT NULL, "accessToken" TEXT, "refreshToken" TEXT, "tokenExpiresAt" DATETIME, "followerCount" INTEGER NOT NULL DEFAULT 0, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS "content_themes" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "description" TEXT, "color" TEXT NOT NULL DEFAULT '#3B82F6', "contentRatio" REAL NOT NULL DEFAULT 0.25, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS "content_series" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "themeId" TEXT NOT NULL, "frequency" TEXT NOT NULL DEFAULT 'WEEKLY', "dayOfWeek" INTEGER, "timeOfDay" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, FOREIGN KEY ("themeId") REFERENCES "content_themes" ("id"))`,
  `CREATE TABLE IF NOT EXISTS "social_posts" ("id" TEXT NOT NULL PRIMARY KEY, "socialAccountId" TEXT NOT NULL, "content" TEXT NOT NULL, "platform" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'DRAFT', "scheduledAt" DATETIME, "publishedAt" DATETIME, "mediaUrls" TEXT NOT NULL DEFAULT '[]', "hashtags" TEXT NOT NULL DEFAULT '[]', "metrics" TEXT NOT NULL DEFAULT '{}', "contentThemeId" TEXT, "contentSeriesId" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, FOREIGN KEY ("socialAccountId") REFERENCES "social_accounts" ("id") ON DELETE CASCADE, FOREIGN KEY ("contentThemeId") REFERENCES "content_themes" ("id") ON DELETE SET NULL, FOREIGN KEY ("contentSeriesId") REFERENCES "content_series" ("id") ON DELETE SET NULL)`,
  `CREATE TABLE IF NOT EXISTS "post_approvals" ("id" TEXT NOT NULL PRIMARY KEY, "socialPostId" TEXT NOT NULL, "userId" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'PENDING', "comment" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("socialPostId") REFERENCES "social_posts" ("id") ON DELETE CASCADE, FOREIGN KEY ("userId") REFERENCES "users" ("id"))`,
  `CREATE TABLE IF NOT EXISTS "lead_gen_campaigns" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'DRAFT', "targetProfile" TEXT NOT NULL DEFAULT '{}', "scrapingStrategy" TEXT NOT NULL DEFAULT '{}', "resultsSummary" TEXT NOT NULL DEFAULT '{}', "targetLeadCount" INTEGER NOT NULL DEFAULT 500, "budget" REAL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS "scraped_leads" ("id" TEXT NOT NULL PRIMARY KEY, "leadGenCampaignId" TEXT NOT NULL, "contactId" TEXT, "rawData" TEXT NOT NULL DEFAULT '{}', "enrichmentData" TEXT NOT NULL DEFAULT '{}', "fitScore" INTEGER NOT NULL DEFAULT 0, "intentScore" INTEGER NOT NULL DEFAULT 0, "engagementScore" INTEGER NOT NULL DEFAULT 0, "totalScore" INTEGER NOT NULL DEFAULT 0, "grade" TEXT NOT NULL DEFAULT 'D', "status" TEXT NOT NULL DEFAULT 'NEW', "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, FOREIGN KEY ("leadGenCampaignId") REFERENCES "lead_gen_campaigns" ("id") ON DELETE CASCADE, FOREIGN KEY ("contactId") REFERENCES "contacts" ("id") ON DELETE SET NULL)`,
  `CREATE TABLE IF NOT EXISTS "scraping_sources" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "type" TEXT NOT NULL, "apiKey" TEXT, "costPerLookup" REAL NOT NULL DEFAULT 0, "totalLookups" INTEGER NOT NULL DEFAULT 0, "successRate" REAL NOT NULL DEFAULT 0, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS "target_profiles" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "criteria" TEXT NOT NULL DEFAULT '{}', "createdById" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, FOREIGN KEY ("createdById") REFERENCES "users" ("id"))`,
  `CREATE TABLE IF NOT EXISTS "lead_scores" ("id" TEXT NOT NULL PRIMARY KEY, "contactId" TEXT NOT NULL, "fitScore" INTEGER NOT NULL DEFAULT 0, "intentScore" INTEGER NOT NULL DEFAULT 0, "engagementScore" INTEGER NOT NULL DEFAULT 0, "totalScore" INTEGER NOT NULL DEFAULT 0, "grade" TEXT NOT NULL DEFAULT 'D', "scoringDetails" TEXT NOT NULL DEFAULT '{}', "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("contactId") REFERENCES "contacts" ("id") ON DELETE CASCADE)`,
  `CREATE TABLE IF NOT EXISTS "email_sequences" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "type" TEXT NOT NULL, "steps" TEXT NOT NULL DEFAULT '[]', "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS "email_sequence_enrollments" ("id" TEXT NOT NULL PRIMARY KEY, "sequenceId" TEXT NOT NULL, "contactId" TEXT NOT NULL, "currentStep" INTEGER NOT NULL DEFAULT 0, "status" TEXT NOT NULL DEFAULT 'ACTIVE', "enrolledAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "completedAt" DATETIME, FOREIGN KEY ("sequenceId") REFERENCES "email_sequences" ("id") ON DELETE CASCADE, FOREIGN KEY ("contactId") REFERENCES "contacts" ("id") ON DELETE CASCADE)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "users_email_key" ON "users"("email")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "contacts_email_key" ON "contacts"("email")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "campaign_metrics_campaignId_date_key" ON "campaign_metrics"("campaignId", "date")`,
];

async function main() {
  console.log("Pushing schema to Turso...");
  for (const sql of statements) {
    try {
      await client.execute(sql);
      const table = sql.match(/"(\w+)"/)?.[1];
      console.log(`  ✓ ${table}`);
    } catch (err) {
      console.error(`  ✗ Error: ${err.message}`);
      console.error(`    SQL: ${sql.substring(0, 80)}...`);
    }
  }
  console.log("Done!");
}

main().catch(console.error);
